variable "env" {}
variable "tags" {}
variable "vpc_id" {}
variable "app_subnets_cidr" {}
variable "ssh_subnets_cidr" {}
variable "sg_port" {}
variable "instance_type" {}
variable "zone_id" {}
variable "db_subnets_ids" {}
variable "kms_key_arn" {}
