// Run the terraform code
pipeline {
  agent any
    // Ansi Colour options
  options {
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }

  parameters {
    string(name: 'ENV', defaultValue: 'prod', description: 'Environment')
  }


  stages {
    stage('Terraform Apply') {
      steps {
        sh 'cd Terraform-RoboShop/roboshop-terraform/ ; make ${ENV}'
      }
  }}
}



