- name: Create Multi Branch Pipeline Jobs.
  ansible.builtin.include_tasks:
    file: mjob.yml
  loops: "{{ mjob }}"


- name: Create Single Branch Pipeline Jobs.
  ansible.builtin.include_tasks:
    file: sjob.yml
  loops: {{ sjob }}
