- name: Create Multi Branch Pipeline Jobs.
  ansible.builtin.include_tasks:
    file: mjob.yml
  loop: "{{ mjob }}"


- name: Create Single Branch Pipeline Jobs.
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop: "{{ sjob }}"
