- name: Copy Multibranch_Pipeline Config File - {{ item.job_name}}.
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/mjob.xml

- name: Create a Multibranch_Pipeline jenkins job - {{ item.job_name}}.
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mjob.xml') }}"
    name: "{{ item.job_name}}"
    password: DevOps321
    url: http://172.31.19.166:8080/
    user: admin