variable "env" {}
variable "tags" {}
variable "rds_type" {}
variable "db_subnets_ids" {}
variable "vpc_id" {}
variable "app_subnets_cidr" {}
variable "family" {}
variable "sg_port" {}
variable "engine" {}
variable "engine_version" {}
variable "backup_retention_period" {}
variable "preferred_backup_window" {}
variable "skip_final_snapshot" {}
variable "instance_count" {}
variable "instance_class" {}
