pipeline {
    agent any

    stages {

        stage('Test_Branch') {
            steps {
                echo 'Test'

        stage('Main_Branch') {
            steps {
                echo 'Compile'

            }
        }
        stage('Compile') {
            steps {
                echo 'Compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }

    }
}
