pipeline {
    // agent any
    agent { node { label 'workstation' } }

    stages {

        stage('Compile') {
            steps {
                echo 'Compiling The Code.'
            }
        }

        stage('Test') {
            steps {
                echo 'Test The Code.'

            }
        }
        stage('Code Quality') {
            steps {
                echo 'Code Quality'
            }
        }
        stage('Code Security') {
            steps {
                echo 'Code Security'
            }
        }
        stage('Deployment') {
            steps {
                echo 'Code Deployment'
            }
        }

    }
    post {
        always {
            echo 'post'
            // Send Email
            // Trigger Some another job
            // Update some JIRA Status about the build.
    }
    }
}

