- name: Set a Hostname
  ansible.builtin.hostname:
    name: elk

- name: Copying ElasticSearch Repo File
  ansible.builtin.template:
    src: "elasticsearch.repo"
    dest: /etc/yum.repos.d/

- name: Installing ElasticSearch, Kibana & Nginx
  ansible.builtin.yum:
    name:
      - elasticsearch
      - kibana
      - nginx
      - bash-completion
    state: installed

- name: Restart ElasticSearch Service.
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted
    enabled: yes
    daemon_reload: true
