# To install whole maven, it's taking time which is not required, so we are only installing java-17-openjdk, and also maven is not required because artifact coming with dependency handled with jenkins.

#- name: Installing the Maven and MySql.
#  ansible.builtin.yum:
#    name:
#      - maven
#      - mysql
#    state: installed

- name: Installing the Maven and MySql.
  ansible.builtin.yum:
    name:
      - java-17-openjdk
      - mysql
    state: installed

- name: Importing App Prerequisite Tasks.
  ansible.builtin.import_tasks: appprereq.yml

#- name: Downloading Dependencies and making artifact.
#  ansible.builtin.shell: mvn clean package; mv /app/target/{{component}}-1.0.jar /app/{{component}}.jar
#  args:
#    chdir: /app

- name: Importing Schema Setup Tasks.
  ansible.builtin.import_tasks: mysql_schema.yml
  when: schema is defined

- name: Importing Systemd Setup Tasks.
  ansible.builtin.import_tasks: systemd.yml

- name: Filebeat Configuration
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

