- name: Check nodejs is installed or not.
  ansible.builtin.shell: type npm
  register: command_status
  ignore_errors: yes

- name: Disable current nodejs module.
  ansible.builtin.shell: dnf module disable nodejs -y
  when: command_status.rc != 0

- name: Enable current nodejs module.
  ansible.builtin.shell: dnf module enable nodejs:18 -y
  when: command_status.rc != 0

- name: Installing NodeJS.
  ansible.builtin.yum:
    name: nodejs
    state: latest
  when: command_status.rc != 0

- name: Catalogue Configuration
  ansible.builtin.import_tasks: appprereq.yml

# Dependency installation is not required for nodejs because it's taken care by jenkins. Artifact is coming with packed dependency.
#- name: Installing the application dependency.
#  ansible.builtin.shell: npm install
#  args:
#    chdir: /app

- name: Schema setup
  ansible.builtin.import_tasks: schema.yml
  when: schema is defined

- name: Systemd {{component}} service setup.
  ansible.builtin.import_tasks: systemd.yml

- name: Filebeat Configuration
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat
